// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.morec.springmvcroobook.myrooapp.mydata;

import at.morec.springmvcroobook.myrooapp.mydata.MyDataDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MyDataDataOnDemand_Roo_Configurable {
    
    declare @type: MyDataDataOnDemand: @Configurable;
    
}
